name: Build webOS IPK (via Script)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout del codice (tuo fork)
        uses: actions/checkout@v4

      - name: Installa dipendenze base
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make pkg-config wget git python3 npm curl protobuf-compiler

      - name: Installa ares-cli (LG Tools)
        run: sudo npm install -g @webos-tools/cli

      - name: Scarica e installa webOS NDK
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/webosbrew/meta-lg-webos-ndk/releases/latest | grep "browser_download_url.*\.sh" | cut -d '"' -f 4 | head -n 1)
          wget -q $DOWNLOAD_URL -O ndk-installer.sh
          chmod +x ndk-installer.sh
          ./ndk-installer.sh -y -d /opt/webos-sdk

      - name: Prepara il codice originale di chiaki-ng
        run: |
          cd ..
          git clone --recursive https://github.com/streetpea/chiaki-ng.git

      - name: Avvia lo script di build automatico
        run: |
          # Definiamo la cartella base come preteso dallo script
          export TOOLCHAIN_DIR=/opt/webos-sdk
          
          # 1° Trucco: Diamo allo script il toolchainfile.cmake che cerca
          REAL_TOOLCHAIN=$(find /opt/webos-sdk -name "OEToolchainConfig.cmake" | head -n 1)
          sudo mkdir -p /opt/webos-sdk/share/buildroot
          sudo ln -s $REAL_TOOLCHAIN /opt/webos-sdk/share/buildroot/toolchainfile.cmake
          
          # 2° Trucco: Diamo allo script il nome esatto del file environment-setup
          sudo ln -s /opt/webos-sdk/environment-setup-* /opt/webos-sdk/environment-setup
          
          # 3° Trucco: Inizializziamo la variabile che fa andare in crash lo script e togliamo la modalità paranoia a bash
          export CCACHE_PATH=""
          export PKG_CONFIG_PATH=""
          sed -i 's/set -eu/set -e/g' build-webos.sh
          sed -i 's/set -u//g' build-webos.sh
          
          # Avviamo finalmente lo script
          chmod +x build-webos.sh
          ./build-webos.sh ../chiaki-ng

      - name: Salva il file .ipk
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-lg-ipk
          path: "**/*.ipk"
