name: Build webOS IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout del tuo repository
        uses: actions/checkout@v4

      - name: Installa dipendenze di sistema e codec audio/video
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config wget git curl \
            python3 python3-pip protobuf-compiler \
            nasm yasm libtool autoconf automake nodejs npm
          sudo npm install -g @webos-tools/cli
          pip3 install "protobuf<4"

      - name: Installa webOS NDK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DOWNLOAD_URL=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/webosbrew/meta-lg-webos-ndk/releases/latest | grep "browser_download_url.*\.sh" | cut -d '"' -f 4 | head -n 1)
          
          if [ -z "$DOWNLOAD_URL" ]; then
            echo "API fallita, uso il link di download diretto..."
            DOWNLOAD_URL="https://github.com/webosbrew/meta-lg-webos-ndk/releases/latest/download/meta-webos-smack-x86_64-armv7a-neon-webos-linux-gnueabi-toolchain-1.0.sh"
          fi
          
          wget -q "$DOWNLOAD_URL" -O ndk-installer.sh
          chmod +x ndk-installer.sh
          sudo ./ndk-installer.sh -y -d /opt/webos-sdk
          
          sudo chown -R $USER:$USER /opt/webos-sdk

      - name: Clona il codice sorgente di chiaki-ng
        run: |
          cd ..
          git clone --recursive https://github.com/streetpea/chiaki-ng.git

      - name: Esecuzione script di compilazione
        run: |
          export TOOLCHAIN_DIR=/opt/webos-sdk
          chmod +x build-webos.sh
          ./build-webos.sh ../chiaki-ng

      - name: Upload del file .ipk
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-lg-ipk
          path: "**/*.ipk"
